covertool/covertool

src/covertool.erl, src/rebar_covertool.erl
Just separate them with commas. :) Useful when creating a report for release consisting of more than one application.
Unfortunately I don't have time right now to write proper tests for this. :(
=> Support for multiple src and beam paths

Makefile, README.md, test/rebar_covertool_tests.erl
OTP-12031 explains that previous "fix" OTP-11971 (introduced in 17.1) broke path handling in cover. This PR fixes the relative path in the test.
=> Fix for OTP 17.4

Makefile, README.md, src/covertool.erl, test/rebar_covertool_tests.erl
Goes on top of #18 
I haven't noticed in previous PR that printing a list of sources in XML file got broken by multipath.
=> Multipath fix

rebar.config
Rebar 2.5.1 have some issues with recursive coverage and common tests. 2.6.0 works well.
=> Update rebar to 2.6.0

Makefile
If $REBAR is defined, assume rebar already exists,
and is built outside of this Makefile.
This fixes our build for a dependent project where DEPS_DIR
is set to a root dir not in this particular app.
=> Only fetch rebar if $(REBAR) undefined

Makefile
I repositioned the 'deps' target in a previous commit,
that added an ifdef in case REBAR was already defined:
71dd390e8222c0dbbcc376564910ef03210aa46d
However, I didn't realize that Makefiles depend on having
their default targets always at the top (it doesn't just always
magically default to 'all').
Therefore, this restores the intended order of the targets.
=> Makefile: Move 'all' back to top so its default

src/covertool.erl
Hi, 
We use this tool at my company for coverage analysis on our Erlang projects. Unfortunately, much of our code is still pinned to R16B03-1. The latest commit to this repo for R18 compatibility broke R16 compatibility, because `erlang:timestamp/0` is not available.
I have updated timestamp calculation to use `os:timestamp/0` rather than `erlang:timestamp/0`. This allows compatibility with both R18 and R16.
Thanks in advance for reviewing.
=> Restore covertool compatibility with R16

rebar.config.script
Make compatible with rebar3 (and incompatible versions of rebar2)
by removing the dependency on rebar unless we are building directly.
=> Compatibility with rebar3

rebar.config
When included in other projects, with rebar2, the untyped config
record causes error... don't let it.
=> Ensure untyped record doesn't error

.gitignore, src/rebar3_covertool_gen.erl, src/rebar_covertool.erl
The `rebar_covertool` module now supports both rebar2 and rebar3
plugin interfaces.  For rebar3, output is generated into a rebar3
standard location: _build/test/covertool/*.covertool.xml.
=> Implement rebar3 plugin

src/rebar3_covertool_gen.erl
Without this patch generation of xml  fails silently when one of ct/eunit.coverdata files is missing.
=> Improve error reporting and handling of missing files

src/rebar3_covertool_gen.erl
Sorry, I was to hasty to submit #31. Missed the fact that it wasn't
generating any output at all - just happily skipping every file because
it was considered non-existing unconditionally.
=> Fix missing files filter

README.md, src/rebar3_covertool_gen.erl
This change introduces the `include_apps` option to the rebar3 covertool pluigin, to allow users to specify a list of dependent apps to also generate cobertura coverage reports for. This can be very helpful if you have some libraries that cannot be effectively tested on their own, but are tested via ct in a higher level test.
As the README notes, you'll only get coverage data if you include the beams from the deps in your initital coverage report. However, this allows you to bring the data already included (separately) in the `.coverdata` file into a Cobertura report that is keyed by application name.
Lastly, this fixes a bug introduced by idubrov/covertool#35, where the ebin directory for applications weren't included in the rebar3 coverage report, causing empty reports to be generated.
=> Add include_apps option to allow including additional dependencies to rebar3 coverage reports

README.md, src/covertool.erl, src/rebar3_covertool_gen.erl
This change adds support for passing the `prefix_len` configuration parameter into the `covertool` section of the rebar3 `rebar.config` file, for parity with the `covertool_prefix_len` option from rebar2.
This also introduces a package naming adjustment strip out tedious rebar3 source path segments from the package name. For example, where before you might have a package name like `app0._build.default.lib.app0.src`, this would be replaced with simply `app0` as the package name. Outside rebar3 paths, there should be no change. This is compatible with the prefix_len support as well.
=> Add support for `prefix_len` in rebar3 plugin, remove rebar3 boilerplate in package names

include/covertool.hrl, src/covertool.erl, src/mix_covertool.erl, src/rebar3_covertool_gen.erl
* Restores the `#config.sources` argument removed in #35. Now, however, this is only used for forming "relative" paths to the source files in package names. As such, it's "optional."
* Consolidates the default values for `#config.sources` into the covertool.hrl
* Implements a new source path check for trimming the absolute path off of source files. This works identically to the previous version, but integrates with @tverlaan's change to lookup the source using `beam_lib:chunks/2`.
* Updates `rebar3_covertool_gen` to set `#config.sources` for the `src` dir for the current and default profiles, since it seems that the compiled beams typically reference the path in the default directory
* Updates `mix_covertool` to set `#config.sources` as the `cwd`, so that it should work as previously.
=> Restore "sources" argument to config

README.md, src/covertool.app.src
Resolves #42. This change introdoces covertool as 2.0.0, to avoid any confusion with the `rebar_covertool` package version.
=> Rename covertool package

src/covertool.erl
Azure DevOps CI fails to read the file if the `branch` field is not specified. Since the feature of branching does not seem to be supported at the moment by the tool, I set it to `false`.
=> Add missing `branch` field in lines

.travis.yml, Makefile, README.md, rebar.config, rebar.config.script, src/covertool.app.src, test/rebar_covertool_tests.erl
* Refactor unit tests to build the test application and execute using the client's provided eunit command (use `os:find_executable/1` to get it if it's not provided as a full path in the `$REBAR` environment variable)
* Fix the unit tests to be compatible with the latest output format.
* Remove rebar as an explicit dependency
* Update app.src version to 2.0.1
* Support building with travis-ci
* Resolves #44
=> Fix unit tests and remove rebar dependency

src/covertool.app.src
Removes this deprecated property so that we can continue to publish covertool as a Hex package.
=> Hex pkg: Remove deprecated "maintainers" property

README.md
I have set up travis-ci on my personal fork, https://github.com/nalundgaard/covertool/, in order to verify the travis file. That is [working nicely](https://travis-ci.org/nalundgaard/covertool/builds/585593798). Now I would like to have travis-ci set up for the mainline project, and linked in the README, as this change optimistically references.
@idubrov this is contingent on you (as an owner of the covertool organization) accepting the request I have made to add travis-ci access. Alternately, you could make me an owner of the covertool organization so that I can take care of this.
=> Fix covertool link in README

.travis.yml
I forgot to include this new Erlang release in the original PR (#52).
=> Add Erlang/OTP 22 to .travis.yml

.gitignore, Makefile, rebar.config, test/rebar_covertool_tests.erl
* rebar 2.6.0+ is still required to be installed for unit tests to pass
* Sets the stage to build rebar3-based tests too
=> Update Makefile to use rebar3

src/covertool.erl
fixes https://github.com/covertool/covertool/issues/57.
=> covertool escript: don't import coverdata twice

src/covertool.erl
Fixes https://github.com/covertool/covertool/issues/60
=> Allow for missing 'source' in 'compile_info'

README.md, include/covertool.hrl, src/covertool.erl, src/mix_covertool.erl, src/rebar3_covertool_gen.erl, src/rebar_covertool.erl
It was happening (in Elixir, so I assume macros) that some lines were repeated in the output which could confuse some parsers. Now it will squash them by summing up the call count.
=> Squash repeated lines

src/covertool.erl
When passing a relative path to `-src` argument the source path in the generated XML is correctly transformed to an absolute one but class paths remain absolute when they should be relative to the ones of the source. This happens because class paths are calculated before transforming source ones to absolute.
=> Store abspath of src dirs so that class paths are correctly relative

src/covertool.app.src
`xmerl` and `tools` (containing the `cover` module) are missing from the application configuration, which leads to compilation issue if used with elixir 1.15.
Would it be possible to patch it and issue a new version on hex? Thanks!
=> Update application configuration to make it compatible with Elixir 1.15

include/covertool.hrl, src/covertool.erl
Thank you for the great tool.
We are trying to use this as a embedded component in our project.
The `lookup_source/1` is not working for us, because we enable `deterministic` compilation flag,
When `deterministic` is used, source file is not found in `compile_info`.
In this PR, I try to build a module to source mapping before the call, and provide a callback from the config.
Hope this can help others too.
=> Allow user provided source file lookup function
